import React, { useState, useEffect } from "react";
import Head from 'next/head';
import TableUpperHeader from "./shared/tableUpperHeader";
import styles from '../styles/Home.module.scss';
import style from '../styles/UserAdminMgt.module.scss';


const Participant = () => {
    const options = [1,2,3,4,5,6,7,8,9,10];
    const moduleStatus = ["Private", "Public"];
    
    const editIcon = <svg width="8" height="12" viewBox="0 0 8 12" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fillRule="evenodd" clipRule="evenodd" d="M6.30996 0.765625C6.20411 0.765625 6.09403 0.824723 6.01358 0.93701L5.23877 2.01851L6.8265 4.23469L7.60132 3.1532C7.76644 2.92271 7.76644 2.55039 7.60132 2.31991L6.61057 0.93701C6.52589 0.818813 6.42004 0.765625 6.30996 0.765625ZM4.78479 4.32104L5.17431 4.86474L1.33837 10.219H0.948847V9.6753L4.78479 4.32104ZM0.101562 9.18721L4.78429 2.65105L6.37202 4.8672L1.68929 11.4034H0.101562V9.18721Z" fill="#20C997"/>
    </svg>
    
    const deleteIcon = <svg width="9" height="12" viewBox="0 0 9 12" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fillRule="evenodd" clipRule="evenodd" d="M6.18398 0.839844L6.76667 1.42253H8.80608V2.58791H0.648438V1.42253H2.68785L3.27054 0.839844H6.18398ZM1.23006 10.162C1.23006 10.803 1.75448 11.3274 2.39544 11.3274H7.05695C7.6979 11.3274 8.22232 10.803 8.22232 10.162V3.16975H1.23006V10.162ZM2.39673 4.33471H7.05823V10.1616H2.39673V4.33471Z" fill="#DC3545" fillOpacity="0.54"/>
    </svg>
    
    const cancelIcon = <svg width="120" height="122" viewBox="0 0 120 122" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g filter="url(#filter0_d)">
    <rect x="45.1016" y="52.7773" width="35.7089" height="30.9439" fill="white"/>
    </g>
    <path d="M69.625 62.7381L68.215 61.3281L62.625 66.9181L57.035 61.3281L55.625 62.7381L61.215 68.3281L55.625 73.9181L57.035 75.3281L62.625 69.7381L68.215 75.3281L69.625 73.9181L64.035 68.3281L69.625 62.7381Z" fill="black" fillOpacity="0.54"/>
    <defs>
    <filter id="filter0_d" x="0.101562" y="0.777344" width="125.709" height="120.944" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
    <feFlood floodOpacity="0" result="BackgroundImageFix"/>
    <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
    <feOffset dy="-7"/>
    <feGaussianBlur stdDeviation="22.5"/>
    <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0"/>
    <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
    <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
    </filter>
    </defs>
    </svg>
    
    const sortIcon = <svg width="9" height="12" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M1.45287 8.14062L0.46875 9.12475L4.6565 13.3125L8.84426 9.12475L7.86013 8.14062L4.6565 11.3373L1.45287 8.14062Z" fill="#BDBDBD"/>
    <path d="M7.85572 5.3125L8.83984 4.32838L4.65209 0.140625L0.464337 4.32838L1.44846 5.3125L4.65209 2.11585L7.85572 5.3125Z" fill="#BDBDBD"/>
    </svg>
    
    let count: number = 1;
    
    const tableInfo = [
        { id: count++, moduleName: "Self Esteem", duration: 30,   status: "active" },
        { id: count++, moduleName: "Productivity", duration: 30,   status: "inactive" },
        { id: count++, moduleName: "Gender Based Violence", duration: 10,   status: "pending" },
        { id: count++, moduleName: "Human Right", duration: 5,   status: "active" },
        { id: count++, moduleName: "Child Abuse", duration: 25,   status: "pending" },
        { id: count++, moduleName: "Low Fidelity", duration: 15,   status: "active" },
        { id: count++, moduleName: "Marital Delay", duration: 30,   status: "inactive" },
        { id: count++, moduleName: "Domestic Violence", duration: 20,   status: "active" },
        { id: count++, moduleName: "Assault", duration: 10,   status: "pending" },
        { id: count++, moduleName: "Self Reliance", duration: 5,   status: "inactive" },
        
    ];
    
    const name = `Create Module`;
    
    const [createFamModule, setFamModule] = useState(false);
    
    console.log("CreateModStat::::", createFamModule);
    
    const handleCreateModule = (e: any) => {
        e.preventDefault();
        console.log(`Creating NEW MODULE++++++`);
        
        setFamModule(true);
        
        setTimeout(() => {
            setFamModule(false);
        }, 5000);
    }
    
    const handleCloseCreateModuleDiv = (e: any) => {
        e.preventDefault();
        console.log(`Closing CREATE NEW MODULE +++++++++`);
        
        setFamModule(false);
    }
    
    return (
        <React.Fragment>
            <div className={ styles.admin_dashboard_container}>
                <Head>
                    <title>FAM ADMIN DASHBOARD</title>
                    <meta name="description" content="Generated by create next app" />
                    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' />
                    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" />
                </Head>
                <div className={ styles.admin_welcome_msg}>
                    <h3>Welcome Admin</h3>
                    <span>Dashboard - </span><span>FAM Modules</span>
                </div>
                <div className={ style.main_fam_module_control}>
                    <div className={ style.fam_module_control}>
                        <div className={ style.fam_table_top_div_1}>
                            <TableUpperHeader
                                createModule={(e: any) => handleCreateModule(e)}
                                name={name}
                            />
                        </div>
                        
                        <div className={`${style.create_module_main} ${createFamModule ? style.create_module_main_show : style.create_module_main_hide }`}>
                            <div className={style.create_module_sub_main}>
                                <span className={style.create_module_sub_text}>Create New Module</span>
                                <span className={style.create_module_sub_icon} onClick={(e) => handleCloseCreateModuleDiv(e)}>{cancelIcon}</span>
                            </div>
                            <div className={style.create_module_inputs}>
                                <input name="mod_name" placeholder="Module Name" className={style.create_module_input_1}/>
                                <input name="mod_name" placeholder="Duration" className={style.create_module_input_2}/>
                                <select name="stat" id="stat" className={style.create_module_select}> 
                                    <option value="" >Module Status</option>
                                    {
                                        moduleStatus.map(stat => <option key={stat} value={stat}>{stat}</option>)
                                    }
                                </select>
                                <div className={style.btn_create_module_div}>
                                    <button className={style.btn_create_module}>Submit Module</button>
                                </div>
                            </div>
                        </div>
                        <div className={ style.fam_table_top_div_2}>
                            <table className={ style.fam_table_main}>
                                <thead className={ style.fam_table_main_header}>
                                    <tr className={ style.fam_table_main_header_row }>
                                        <th className={style.fam_table_main_header_col_1}>S/N<span className={style.fam_table_main_sort_1}>{sortIcon}</span></th>
                                        <th className={style.fam_table_main_header_col_2}>MODULE NAME<span className={style.fam_table_main_sort_2}>{sortIcon}</span></th>
                                        <th className={style.fam_table_main_header_col_3}>DURATION<span className={style.fam_table_main_sort_3}>{sortIcon}</span></th>
                                        <th className={style.fam_table_main_header_col_4}>STATUS</th>
                                        <th className={style.fam_table_main_header_col_5}>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody className={ style.fam_table_main_body}>
                                    { tableInfo.map((info) => 
                                        <tr key={info.id} className={ style.fam_table_main_body_row }>
                                            <td className={style.fam_table_main_body_col_1}>{info.id}</td>
                                            <td className={style.fam_table_main_body_col_2}>{info.moduleName}</td>
                                            <td className={style.fam_table_main_body_col_3}>{info.duration}</td>
                                            <td className={style.fam_table_main_body_col_4}>{info.status}</td>
                                            <td className={style.fam_table_main_body_col_5}>
                                                <button className={style.btn_fam_mod_1}><span className={style.btn_span}>{editIcon}</span>Edit</button>
                                                <button className={style.btn_fam_mod_2}><span className={style.btn_span}>{deleteIcon}</span>Delete</button>
                                            </td>
                                        </tr>
                                    )}
                                </tbody>
                            </table>
                            <div className={style.pagination_div}>
                                <div className={style.pagination_text}>
                                    <span className={style.pagination_text_span}><small>showing {1} to {10} of {58} entries</small></span>
                                </div>
                                <div ></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    )
}

export default Participant;