import React from "react";
import Head from 'next/head';
import style from '../styles/Home.module.scss';
import styles from '../styles/UserAdminMgt.module.scss';


const Participant = () => {
    return (
        <React.Fragment>
            <div className={style.container}>
                <Head>
                    <title>FAM ADMIN DASHBOARD</title>
                    <meta name="description" content="Generated by create next app" />
                    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' />
                </Head>
                <h1>Participants.....</h1>
            </div>
        </React.Fragment>
    )
}

export default Participant;