import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/shared/Layout';
import Dashboard from '../components/Dashboard';
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FAM ADMIN DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" />
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'></link>
      </Head>
      <Layout title={`Main Layout`}>
        <Dashboard />
      </Layout>
    </div>
  )
}
